version: '3'

services:
  compiler:
    build: .
    volumes:
      - var/run/docker.sock:var/run/docker.sock
    depends_on:
      - consul
    networks:
      - brige

  consul:
    image: minhcuong/alpine-consul
    networks:
      - brige

networks:
  brige: