version: '3'

services:
  compiler:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
    networks:
      - techmaster

  consul:
    image: minhcuong/alpine-consul
    networks:
      - techmaster

  consului:
    image: minhcuong/alpine-consul-ui
    ports:
      - 8500:8500
    networks:
      - techmaster

networks:
  techmaster: